### ISSUE TITLE
Dead players block bullets

### ISSUE THREAD

**Issue by NotHosomi** [Rainyan/sourcemod-nt-respawns#13]
After a player has died, their hitboxes seem to remain and block bullets that pass through the air where they are "standing" 
Potential solution: teleport dead players to a location away from the playspace, however this would only work if the map has a dead player teleport location specified.

**To Reproduce**
Kill a player
Shoot through the air in the space where they died

**Expected behavior**
Bullets should pass through the space without being absorbed

**Additional context**
Observed during the showmatch playtest

**Comment by Rainyan** [comment]
Thanks for the report! Somehow toggling the player solidity would probably be the nicest way to fix this without resorting to teleporting.

**Comment by Rainyan** [comment]
Unable to reprod

[penbug_.webm](https://github.com/Rainyan/sourcemod-nt-respawns/assets/6595066/534ab343-e6ed-459b-9f4a-711b855ef19d)

**Comment by Rainyan** [comment]
@NotHosomi Could you upload the 1st person demo of the showmatch where this occurred, if you still have it?

**Comment by Rainyan** [comment]
Closing this as unactionable. If you have more info, feel free to reopen/comment/submit new issue

**Comment by Rainyan** [comment]
For posterity, the relevant code has been moved to a new repo: https://github.com/Rainyan/sourcemod-nt-deadtools

Please open any new related issues there.
